version: '3.8'

services:
  voicevox_engine:
    container_name: vsa-voicevox-engine
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    ports:
      - '50021:50021'
    tty: true

  fastapi_app:
    container_name: vsa-fastapi-app
    build: ./app
    ports:
      - '8000:8000'
    volumes:
      - ./app:/app
    depends_on:
      - voicevox_engine
